jobs:
- template: build-templates/build-package.job.yml
  parameters:
    name: Windows
    vmImage: 'windows-2022'
    publishBuildArtifacts: 'true'
    publishCodeCoverage: 'true'
    
- template: build-templates/build-package.job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-2022'
    publishBuildArtifacts: 'true'
    publishCodeCoverage: 'true'

#- template: build-templates/build-package.job.yml
#  parameters:
#    name: MacOS
#    vmImage: 'macOS-10.14'
#    publishBuildArtifacts: 'false'
#    publishCodeCoverage: 'false'