pool:
  vmImage: 'VS2017-Win2016'
  
trigger:
  batch: true

variables:
  mainProject: 'src/AtleX.HaveIBeenPwned/AtleX.HaveIBeenPwned.csproj'
  unitTestProject: 'src/AtleX.HaveIBeenPwned/AtleX.HaveIBeenPwned.Tests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: restore
    projects: '**/*.csproj'
    arguments: '--configuration $(build.configuration)'

- task: DotNetCoreCLI@2
  displayName: 'Build projects'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(build.configuration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: '$(unitTestProject)'
    arguments: '--configuration $(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: NuGet packages'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

    ArtifactName: 'NuGet packages'


