jobs:
- template: build-templates/build-package.job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'

- template: build-templates/build-package.job.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'

- template: build-templates/build-package.job.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'
    publishBuildArtifacts: 'true'