# Defines a job that builds a solution with optionally 

parameters:
  name: '(Unknown)'  
  vmImage: ''
  buildConfiguration: 'Release'
  publishCodeCoverage: 'false'
  publishBuildArtifacts: 'false'

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
    - checkout: self
      fetchDepth: 1
    - template: build-solution.steps.yml
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
    - template: run-xunit-unit-tests.steps.yml
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        pathToUnitTestProject: '$(Build.SourcesDirectory)/src/**/*.Tests.csproj'
        publishCodeCoverage: ${{ parameters.publishCodeCoverage }}
    - template: run-xunit-integration-tests.steps.yml
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        pathToIntegrationTestProject: '$(Build.SourcesDirectory)/src/**/*.IntegrationTests.csproj'
    - ${{ if eq(parameters.publishBuildArtifacts, 'true') }}:
      - template: publish-nuget-package-artifacts.steps.yml
