# Defines a job that builds a package

parameters:
  name: '(Unknown)'  
  vmImage: ''
  buildConfiguration: 'Release'
  publishBuildArtifacts: 'false' # true to publish the build artifacts; false otherwise

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
    - template: build-package.steps.yml
      parameters:
        buildConfiguration: ${{ parameters.buildConfiguration }}
        publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}